title: DIY Pedal Basics
description: Tutorials and lessons on the fundamentals of DIY pedals and electronics
author: diypedalbasics
email: diypedalbasics@gmail.com
baseurl: ""
url: "https://diypedalbasics.github.io"
theme: minima

markdown: kramdown+
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md

include:
  - _pages

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
